import { useCallback, useEffect, useRef, useState } from 'react';
import type { BoardState } from './model';
import { inNativePanel, initialBoardId, panelRequest } from './nativeBridge';
type Saved={board:BoardState;revision:number;updatedAt?:string};
type Active={boardId:string|null;revision?:number;generation:number};
export type BoardSummary={id:string;title:string;goal:string;example?:boolean};
export async function api<T>(route:string,method='GET',value?:unknown):Promise<T>{if(inNativePanel)return panelRequest<T>(route,method,value);const response=await fetch(route,{method,headers:value===undefined?{}:{'Content-Type':'application/json'},body:value===undefined?undefined:JSON.stringify(value)});const result=await response.json();if(!response.ok)throw new Error(result.error||'操作失败');return result;}
const waiting:BoardState={version:1,id:'waiting',title:'想做什么新产品？',goal:'在 Codex 里说出你的想法，这里会跟着讨论逐渐成形。',inspirations:[],nodes:[],edges:[],messages:[]};
export default function useBoard(){
  const [board,setBoard]=useState<BoardState>(waiting),[boards,setBoards]=useState<BoardSummary[]>([]),[ready,setReady]=useState(false),[error,setError]=useState(''),[revision,setRevision]=useState(0),[following,setFollowing]=useState(true);
  const current=useRef<Saved>({board:waiting,revision:0}),followRef=useRef(true),generation=useRef(-1),requestSerial=useRef(0);
  const accept=useCallback((state:Saved)=>{current.current=state;setBoard(state.board);setRevision(state.revision);setError('');if(!inNativePanel){const url=new URL(location.href);url.searchParams.set('board',state.board.id);window.history.replaceState(null,'',url);}},[]);
  useEffect(()=>{document.title=board.id==='waiting'?'产品白板':`产品白板 · ${board.title}`;},[board]);
  useEffect(()=>{let disposed=false;const serial=++requestSerial.current;void(async()=>{try{const list=await api<BoardSummary[]>('/api/boards');const active=await api<Active>('/api/session');const desired=await initialBoardId();const id=active.boardId||list.find(b=>b.id===desired)?.id;const state=id?await api<Saved>(`/api/boards/${id}`):undefined;if(disposed||serial!==requestSerial.current)return;setBoards(list);generation.current=active.generation;if(state)accept(state);setReady(true);}catch(e){if(!disposed)setError((e as Error).message);}})();return()=>{disposed=true;};},[accept]);
  useEffect(()=>{if(!ready)return;let disposed=false,running=false;const timer=setInterval(async()=>{if(running)return;running=true;const serial=requestSerial.current;try{const active=await api<Active>('/api/session');const id=followRef.current&&active.boardId?active.boardId:current.current.board.id;if(disposed||serial!==requestSerial.current)return;setError('');if(id==='waiting')return;const changed=active.generation!==generation.current||id!==current.current.board.id||!active.boardId;if(!changed)return;const state=await api<Saved>(`/api/boards/${id}`);if(disposed||serial!==requestSerial.current)return;generation.current=active.generation;if(state.revision!==current.current.revision||id!==current.current.board.id)accept(state);setBoards(await api<BoardSummary[]>('/api/boards'));}catch(e){if(!disposed)setError((e as Error).message);}finally{running=false;}},900);return()=>{disposed=true;clearInterval(timer);};},[ready,accept]);
  const openBoard=async(id:string)=>{const serial=++requestSerial.current;followRef.current=false;setFollowing(false);const state=await api<Saved>(`/api/boards/${id}`);if(serial===requestSerial.current)accept(state);};
  const follow=async()=>{const serial=++requestSerial.current;followRef.current=true;setFollowing(true);const active=await api<Active>('/api/session');if(active.boardId){const state=await api<Saved>(`/api/boards/${active.boardId}`);if(serial===requestSerial.current){generation.current=active.generation;accept(state);}}};
  return {board,boards,ready,error,revision,following,openBoard,follow,exportFiles:()=>api<{json:string;markdown:string}>(`/api/boards/${current.current.board.id}/export`,'POST',{})};
}
